/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDealersRouteImport } from './routes/_authenticated/dealers'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedWaitlistRouteImport } from './routes/_authenticated/waitlist'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteFaqRouteImport } from './routes/_site/faq'
import { Route as SiteHowItWorksRouteImport } from './routes/_site/how-it-works'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteReleasesRouteImport } from './routes/_site/releases'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as AuthenticatedDealerIndexRouteImport } from './routes/_authenticated/dealer.index'
import { Route as AuthenticatedDealerScanRouteImport } from './routes/_authenticated/dealer.scan'
import { Route as AuthenticatedDealerStockRouteImport } from './routes/_authenticated/dealer.stock'
import { Route as AuthenticatedDealerWaitlistRouteImport } from './routes/_authenticated/dealer.waitlist'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealersRoute = AuthenticatedDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaitlistRoute = AuthenticatedWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteHowItWorksRoute = SiteHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteReleasesRoute = SiteReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AuthenticatedDealerIndexRoute =
  AuthenticatedDealerIndexRouteImport.update({
    id: '/dealer/',
    path: '/dealer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDealerScanRoute = AuthenticatedDealerScanRouteImport.update({
  id: '/dealer/scan',
  path: '/dealer/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealerStockRoute =
  AuthenticatedDealerStockRouteImport.update({
    id: '/dealer/stock',
    path: '/dealer/stock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDealerWaitlistRoute =
  AuthenticatedDealerWaitlistRouteImport.update({
    id: '/dealer/waitlist',
    path: '/dealer/waitlist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealers': typeof AuthenticatedDealersRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scan': typeof AuthenticatedScanRoute
  '/waitlist': typeof AuthenticatedWaitlistRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/privacy': typeof SitePrivacyRoute
  '/releases': typeof SiteReleasesRoute
  '/terms': typeof SiteTermsRoute
  '/dealer/scan': typeof AuthenticatedDealerScanRoute
  '/dealer/stock': typeof AuthenticatedDealerStockRoute
  '/dealer/waitlist': typeof AuthenticatedDealerWaitlistRoute
  '/dealer/': typeof AuthenticatedDealerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealers': typeof AuthenticatedDealersRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scan': typeof AuthenticatedScanRoute
  '/waitlist': typeof AuthenticatedWaitlistRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/privacy': typeof SitePrivacyRoute
  '/releases': typeof SiteReleasesRoute
  '/terms': typeof SiteTermsRoute
  '/dealer/scan': typeof AuthenticatedDealerScanRoute
  '/dealer/stock': typeof AuthenticatedDealerStockRoute
  '/dealer/waitlist': typeof AuthenticatedDealerWaitlistRoute
  '/dealer': typeof AuthenticatedDealerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_site': typeof SiteRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dealers': typeof AuthenticatedDealersRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/waitlist': typeof AuthenticatedWaitlistRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/how-it-works': typeof SiteHowItWorksRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/releases': typeof SiteReleasesRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/': typeof SiteIndexRoute
  '/_authenticated/dealer/scan': typeof AuthenticatedDealerScanRoute
  '/_authenticated/dealer/stock': typeof AuthenticatedDealerStockRoute
  '/_authenticated/dealer/waitlist': typeof AuthenticatedDealerWaitlistRoute
  '/_authenticated/dealer/': typeof AuthenticatedDealerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dealers'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/scan'
    | '/waitlist'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy'
    | '/releases'
    | '/terms'
    | '/dealer/scan'
    | '/dealer/stock'
    | '/dealer/waitlist'
    | '/dealer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dealers'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/scan'
    | '/waitlist'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy'
    | '/releases'
    | '/terms'
    | '/dealer/scan'
    | '/dealer/stock'
    | '/dealer/waitlist'
    | '/dealer'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dealers'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/scan'
    | '/_authenticated/waitlist'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/faq'
    | '/_site/how-it-works'
    | '/_site/privacy'
    | '/_site/releases'
    | '/_site/terms'
    | '/_site/'
    | '/_authenticated/dealer/scan'
    | '/_authenticated/dealer/stock'
    | '/_authenticated/dealer/waitlist'
    | '/_authenticated/dealer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dealers': {
      id: '/_authenticated/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof AuthenticatedDealersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/waitlist': {
      id: '/_authenticated/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AuthenticatedWaitlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/how-it-works': {
      id: '/_site/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof SiteHowItWorksRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/releases': {
      id: '/_site/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof SiteReleasesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_authenticated/dealer/': {
      id: '/_authenticated/dealer/'
      path: '/dealer'
      fullPath: '/dealer/'
      preLoaderRoute: typeof AuthenticatedDealerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dealer/scan': {
      id: '/_authenticated/dealer/scan'
      path: '/dealer/scan'
      fullPath: '/dealer/scan'
      preLoaderRoute: typeof AuthenticatedDealerScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dealer/stock': {
      id: '/_authenticated/dealer/stock'
      path: '/dealer/stock'
      fullPath: '/dealer/stock'
      preLoaderRoute: typeof AuthenticatedDealerStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dealer/waitlist': {
      id: '/_authenticated/dealer/waitlist'
      path: '/dealer/waitlist'
      fullPath: '/dealer/waitlist'
      preLoaderRoute: typeof AuthenticatedDealerWaitlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealersRoute: typeof AuthenticatedDealersRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedWaitlistRoute: typeof AuthenticatedWaitlistRoute
  AuthenticatedDealerScanRoute: typeof AuthenticatedDealerScanRoute
  AuthenticatedDealerStockRoute: typeof AuthenticatedDealerStockRoute
  AuthenticatedDealerWaitlistRoute: typeof AuthenticatedDealerWaitlistRoute
  AuthenticatedDealerIndexRoute: typeof AuthenticatedDealerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealersRoute: AuthenticatedDealersRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedWaitlistRoute: AuthenticatedWaitlistRoute,
  AuthenticatedDealerScanRoute: AuthenticatedDealerScanRoute,
  AuthenticatedDealerStockRoute: AuthenticatedDealerStockRoute,
  AuthenticatedDealerWaitlistRoute: AuthenticatedDealerWaitlistRoute,
  AuthenticatedDealerIndexRoute: AuthenticatedDealerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SiteRouteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteHowItWorksRoute: typeof SiteHowItWorksRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteReleasesRoute: typeof SiteReleasesRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteHowItWorksRoute: SiteHowItWorksRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteReleasesRoute: SiteReleasesRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
